spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 3002
  error:
    include-binding-errors: always
    include-message: always